spring:
    application:
            name: MSNS
    datasource:
        url: jdbc:mysql://localhost:3306/MSNS?createDatabaseIfNotExist=true&serverTimezone=UTC&&useSSL=false&allowPublicKeyRetrieval=true
        username: spydev
        password: abdul101
    jpa:
        hibernate:
            ddl-auto: update
    properties:
            hibernate:
                    dialect: org.hibernate.dialect.MySQLDialect 
                    formate_sql: true    
server:       
    servlet:
            context-path: /api/v1
            multipart:
                    max-file-size: 20MB
                    max-request-size: 20MB
logging:
    level:
        root: INFO